
name: dep_audit
description: A lightweight dependency & package health auditor for Dart/Flutter projects.
version: 0.1.5
homepage: https://pub.dev/packages/dep_audit
repository: https://github.com/B33b3k/dep_audit
issue_tracker: https://github.com/B33b3k/dep_audit/issues
environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  linux:
  macos:
  windows:
  web:

dependencies:
  args: ^2.4.2
  glob: ^2.1.2
  http: ^1.2.1
  path: ^1.9.0
  pub_semver: ^2.1.4
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.24.0
  coverage: ^1.6.0

executables:
  dep_audit:
